-- CREER D'ABORD LA BASE DE DONNEE: real_time_tracking;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS movements (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  movement_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT user_move FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
